 version: 2
 jobs:
   build:
     docker:
       - image: debian:testing
     steps:
        - checkout
        - run:
            name: Installed prerequisite packages
            command: |
                apt update -q
                apt install -y -q curl wget sudo
        - run:
            name: Setup environment and download files
            command: |
                source ./env.sh
                wget ${GTOO_URL}
        - run:
            name: Extract and copy files
            command: |
                mkdir rootfs
                sudo tar xf $TAR -C rootfs
                sudo cp -f wsl.conf rootfs/etc
                sudo cp -f resolv.conf rootfs/etc
                sudp cp -f make.conf rootfs/etc/portage
                sudo cp -f cpu.sh rootfs
        - run:
            name: Mount directories and chroot
            command: |
                mount -t proc proc proc/
                mount --bind /sys sys
                chroot . sh cpu.sh
                chroot . emerge-webrsync
        - run:
            name: Install packages
            command: |
                chroot . emerge --oneshot -a n sys-devel/gcc
                chroot . emerge --oneshot --usepkg=n -a n sys-devel/libtool
                chroot . emerge --verbose --update --deep --newuse -a n @world
        - run:
            name: Unmount and compress archive
            command: |
                umount ./{sys,proc}
                tar -zcpf ../install.tar.gz *
                chown `id -un` ../install.tar.gz
