 version: 2
 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
     steps:
        - checkout
        - run:
            name: Installed prerequisite packages
            command: |
                sudo apt update -q
                sudo apt install -y -q curl wget xz-utils sudo
        - run:
            name: Setup environment and download files
            command: |
                source ./env.sh
                mkdir rootfs
                wget ${GTOO_URL}
                sudo tar -xf ${TAR} -C rootfs
                sudo cp -f wsl.conf rootfs/etc
                sudo cp -f resolv.conf rootfs/etc
                sudo cp -f make.conf rootfs/etc/portage
                sudo cp -f cpu.sh rootfs
        - run:
            name: Mount directories and chroot
            command: |
                sudo cd ~/rootfs
                sudo mount -t proc proc proc/
                sudo mount --bind /sys sys
                sudo chroot . sh cpu.sh
                sudo chroot . emerge-webrsync
        - run:
            name: Install packages
            command: |
                sudo chroot . emerge --oneshot -a n sys-devel/gcc
                sudo chroot . emerge --oneshot --usepkg=n -a n sys-devel/libtool
                sudo chroot . emerge --verbose --update --deep --newuse -a n @world
        - run:
            name: Unmount and compress archive
            command: |
                sudo umount ./{sys,proc}
                sudo tar -zcpf ../install.tar.gz *
                sudo chown `id -un` ../install.tar.gz
