 version: 2
 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
     steps:
        - checkout
        - run:
            name: Installed prerequisite packages
            command: |
                sudo apt update -q
                sudo apt install -y -q curl wget xz-utils sudo
        - run:
            name: Setup environment and download files
            command: |
                source ./env.sh
                mkdir rootfs
                cd rootfs
                wget ${GTOO_URL}
        - run:
            name: Extract and copy files
            command: |
                tar -xvJf *.tar.xz
                cd ..
                cp -f wsl.conf rootfs/etc
                cp -f resolv.conf rootfs/etc
                cp -f make.conf rootfs/etc/portage
                cp -f cpu.sh rootfs
        - run:
            name: Mount directories and chroot
            command: |
                cd ~/rootfs
                mount -t proc proc proc/
                mount --bind /sys sys
                chroot . sh cpu.sh
                chroot . emerge-webrsync
        - run:
            name: Install packages
            command: |
                chroot . emerge --oneshot -a n sys-devel/gcc
                chroot . emerge --oneshot --usepkg=n -a n sys-devel/libtool
                chroot . emerge --verbose --update --deep --newuse -a n @world
        - run:
            name: Unmount and compress archive
            command: |
                umount ./{sys,proc}
                tar -zcpf ../install.tar.gz *
                chown `id -un` ../install.tar.gz
