name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build script
      run: sudo bash build-x64.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: install.tar.gz
        # Directory containing files to upload
        path: rootfs/targz
